language: node_js

node_js:
  - "10.15.0"

branches:
  only:
    - travis
notifications:
  slack: slmQp677zJPMelisn08se9Cb#general

addons:
  chrome: stable

cache:
  directories:
    - node_modules

before_script:
  - "npm install --no-package-lock"

script:
  - npm test
